name: Build & UI Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run Webdriver UI Tests Project1
      run: dotnet test TestProject1 --no-build --verbosity normal

    - name: Run Webdriver UI Tests Project2
      run: dotnet test TestProject2 --no-build --verbosity normal

    - name: Run Webdriver UI Tests Project3
      run: dotnet test TestProject3 --no-build --verbosity normal
